FROM r-base:4.3.1

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y python3-venv wget sshfs \
    && useradd -ms /bin/bash cc

# switch user
USER cc
WORKDIR /cc

RUN mkdir -p /cc/outputs/outputs

ENV PATH /home/cc/.local/bin:${PATH}

RUN mkdir -p /home/cc/.local/bin

# install connectors
RUN python3 -m venv /home/cc/.local/red \
    && . /home/cc/.local/red/bin/activate \
    && pip install wheel \
    && pip install red-connector-http==1.0 red-connector-ssh==1.3 red-connector-semcon==2.0 red-connector-ftp==1.2 \
    && ln -s /home/cc/.local/red/bin/red-connector-* /home/cc/.local/bin


